### ISSUE TITLE
how to fill other other pixels instead of zero

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [milq/cvrotate2D#3]
hi @milq,
thanks for your code. i wonder how to fill with other pixels instead of zero when rotate the image? so that it does not look like a black background.
thanks.

**Comment by milq** [comment]
@zimenglan-sysu-512, I think you can find the answer at this link:

https://stackoverflow.com/questions/32230252/opencv-keep-background-transparent-during-warpaffine
